# Generated by Django 4.1.4 on 2023-01-22 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Польщователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
