# Generated by Django 4.1.4 on 2022-12-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ads_description_alter_ads_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='address',
            field=models.CharField(max_length=90),
        ),
    ]
